name: new_movie_riverpod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  go_router: ^8.2.0
  envied: ^0.3.0+3
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1
  shimmer: ^3.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  iconly: ^1.0.1
  dio: ^5.2.1+1
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.8.4
  riverpod_infinite_scroll: ^1.0.9
  liquid_pull_to_refresh: ^3.0.1
  flutter_hooks: ^0.18.6
  infinite_scroll_pagination: ^3.2.0
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.1
  flutter_carousel_slider: ^1.1.0
  lottie: ^2.4.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/animations/

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
